/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FnDAnoDBBoq
 */
import { useRouter } from "next/navigation"
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "../ui/select"

export function MyHeader() {
  const router = useRouter()
  return (
    <div className="w-full mx-auto my-4">
      <Select onValueChange={(value) => router.push(`/admin/dashboard/${value}`)} defaultValue="orders">
        <SelectTrigger>
          <SelectValue placeholder="Orders" />
        </SelectTrigger>
        <SelectContent>
          <SelectGroup>
            <SelectItem value="orders">Orders</SelectItem>
            <SelectItem value="products">Manage Products</SelectItem>
            <SelectItem value="add-product">Add Product</SelectItem>
            <SelectItem value="users">Users</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>
    </div>
  )
}
